MVC - JS/Exercício - 1/config/routes.rb
Rails.application.routes.draw do
  resources :musics
  resources :albums
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "albums#index"
end

MVC - JS/Exercício - 1/app/models/album.rb
class Album < ApplicationRecord
    has_many :musics, dependent: :destroy
end

MVC - JS/Exercício - 1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MVC - JS/Exercício - 1/app/models/music.rb
class Music < ApplicationRecord
  belongs_to :album
end

MVC - JS/Exercício - 1/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def index
        @albums = Album.all
    end

    def show
        @album = Album.find(params[:id])
    end

    def new
        @album = Album.new
    end

    def create
        @album = Album.create(album_params)

        redirect_to album_path(@album)
    end

    def edit
        @album = Album.find(params[:id])
    end

    def update
        @album = Album.find(params[:id])
        @album.update(album_params)

        redirect_to album_path(@album)
    end

    def destroy
        @album = Album.find(params[:id])
        @album.destroy

        redirect_to albums_path
    end

    private
        def album_params
    params.require(:album).permit(:name, :artist)
        end

  def current_album
    @album = Album.find(params[:id])
  end
  
end

MVC - JS/Exercício - 1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

MVC - JS/Exercício - 1/app/controllers/musics_controller.rb
class MusicsController < ApplicationController

    def index
        @musics = Music.all
    end

    def show
        @music = Music.find(params[:id])
    end

    def new
        @music= Music.new
    end
    
    def create
        @music = Music.create(music_params)
        
        redirect_to music_path(@music.id)
    end
    
    def edit
        @music = Music.find(params[:id])
    end

    def update
        @music = Music.find(params[:id])
        @music.update(music_params)
    
        redirect_to music_path(@music.id)
    end

    def destroy
        @music= Music.find(params[:id])
        @music.destroy
    
        redirect_to albums_path
    end

    private
        def music_params
            params.require(:music).permit(:name, :explicit, :album_id, :genre)
        end

end

MVC - JS/Exercício - 1/app/helpers/albums_helper.rb
module AlbumsHelper
end

MVC - JS/Exercício - 1/app/helpers/application_helper.rb
module ApplicationHelper
end

MVC - JS/Exercício - 1/app/helpers/musics_helper.rb
module MusicsHelper
end

MVC - JS/Exercício - 1/app/views/albums/edit.html.erb
<h3>Edit an Album</h3>
<%= form_for @album do |f| %>
  <p>Album's New Name: <%= f.text_field :name %></p>
  <p>Enter New Artist's name: <%= f.text_field :artist%></p>

  <%= f.submit %>
<% end %>

MVC - JS/Exercício - 1/app/views/albums/index.html.erb
<table>
  <% @albums.each do |album| %>
    <tr>
      <td id="<%= album.id %>"><%= album.name%></td>
      <td><%= button_to 'Edit', edit_album_path(album), method: 'get'%></td>
      <td><%= button_to 'Remove', album_path(album), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
      <td>-----</td>
      <td><button id="<%= "verde" << (album.id) %>"><i class="fas fa-check-circle"></i></i></button></td>
      <td><button id="<%= "vermelho" << (album.id) %>"><i class="fas fa-times-circle"></i></button></td>
      <td><button id="<%= "preto" << (album.id) %>"><i class="fas fa-undo"></i></button></td>
      <script>
        document.getElementById("<%= "verde" << (album.id) %>").addEventListener('click', function () {
          document.getElementById("<%= album.id %>").style.color = 'green';
        })

        document.getElementById("<%= "vermelho" << (album.id) %>").addEventListener('click', function () {
            document.getElementById("<%= album.id %>").style.color = 'red';
        })

        document.getElementById("<%= "preto" << (album.id) %>").addEventListener('click', function () {
            document.getElementById("<%= album.id %>").style.color = 'black';
        })
      </script>
  <% end %>
</table>
<%= link_to "Add a New Album", new_album_path %>
<p> <%= link_to "Go to Musics", musics_path %> </p>

MVC - JS/Exercício - 1/app/views/albums/new.html.erb
<h3>Create an Album</h3>
<%= form_for @album do |f| %>
  <p>Album's Name: <%= f.text_field :name, placeholder: "Album name" %></p>
  <p>Artist: <%= f.text_field :artist, placeholder: "Artist" %></p>

  <%= f.submit %>
<% end %>

MVC - JS/Exercício - 1/app/views/albums/show.html.erb
<h2>NAME: <%= @album.name %></h2>
<h4>ARTIST: "<%= @album.artist %>"</h4>
<h4>id: "<%= @album.id %>"</h4>
<%= button_to "All Albums", albums_path, method: :get %>
<%= button_to "Edit Album", edit_album_path(@album), method: :get %>
<%= button_to 'Remove Album', album_path(@album), method: 'delete', data: { confirm: 'Are you sure?' } %>

MVC - JS/Exercício - 1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trabalho</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

MVC - JS/Exercício - 1/app/views/musics/edit.html.erb
<h3>Edit a Music/h3>
<%= form_for @music do |f| %>
    <p>New song title: <%= f.text_field :name %></p>
    <p>Explicit: <%= f.check_box :explicit %></p>
    <p>Enter New Album:<%= f.text_field :album_id %></p>
    <p>Enter New Genre:<%= f.text_field :genre %></p>
    
    <%= f.submit %>
<% end %>

MVC - JS/Exercício - 1/app/views/musics/index.html.erb
<table>
  <% @musics.each do |music| %>
    <tr>
      <td><%= link_to music.name, music_path(music) %></td>
      <td></td>
      <td></td>
      <td id="<%= music.id %>", class="fa"></td>
      <td></td>
      <td></td>
      <td><%= button_to 'Edit', edit_music_path(music), method: 'get'%></td>
      <td><%= button_to 'Remove', music_path(music), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
      <td><button id="<%= "like" << (music.id) %>"><i class="fas fa-thumbs-up"></i></button></td>
      <td><button id="<%= "dislike" << (music.id) %>"><i class="fas fa-thumbs-down"></i></button></td>
      <script>
        document.getElementById("<%= "like" << (music.id) %>").addEventListener('click', function () {
          document.getElementById("<%= music.id %>").innerHTML = "&#xf004;"
          });
        document.getElementById("<%= "dislike" << (music.id) %>").addEventListener('click', function () {
          document.getElementById("<%= music.id %>").innerHTML = "&#xf7a9;"
          });
      </script>
  <% end %>
</table>
<%= link_to "Add a music", new_music_path %>
<p> <%= link_to "Go to Albums", albums_path %> </p>

MVC - JS/Exercício - 1/app/views/musics/new.html.erb
<h3>Create a Music</h3>
<%= form_for @music do |f| %>
    <p>Enter the song title: <%= f.text_field :name, placeholder: "music name" %></p>
    <p>Explicit:          <%= f.check_box :explicit %></p>
    <p>Album_id:          <%= f.text_field :album_id, placeholder: "album id" %></p>
    <p>Genre:             <%= f.text_field :genre, placeholder: "genre name" %></p>

    <%= f.submit %>
<% end %>

MVC - JS/Exercício - 1/app/views/musics/show.html.erb
<h2>NAME: <%= @music.name %></h2>
<h4>EXPLICIT: <%= @music.explicit %></h4>
<h4>ALBUM: "<%= @music.album.name %>"</h4>
<h4>GENRE: "<%= @music.genre %>"</h4>
<%= button_to "All Musics", musics_path, method: :get %>
<%= button_to "Edit", edit_music_path(@music), method: :get %>
<%= button_to 'Remove', music_path(@music), method: 'delete', data: { confirm: 'Are you sure?' } %>